const api = '/api/v1';
const $ = (id) => document.getElementById(id);
const esc = (s) => String(s ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const pct = (n) => `${(Number(n || 0) * 100).toFixed(1)}%`;
const date = (v) => v ? new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}) : '—';
async function get(path){const r=await fetch(path);if(!r.ok)throw new Error(await r.text());return r.json()}
function pickCard(p){const pr=p.home_probability!=null?{H:p.home_probability,D:p.draw_probability,A:p.away_probability}:{};return `<article class="pick-card"><p class="eyebrow">${esc(p.model_version||'Model')}</p><div class="teams">${esc(p.home_team||p.home_team_name||'Home')} <span>vs</span> ${esc(p.away_team||p.away_team_name||'Away')}</div><div class="probabilities"><div class="prob"><span>Home</span><b>${pct(pr.H)}</b></div><div class="prob"><span>Draw</span><b>${pct(pr.D)}</b></div><div class="prob"><span>Away</span><b>${pct(pr.A)}</b></div></div><div class="confidence">Prediction: <strong>${esc(p.selected_prediction)}</strong> · Confidence ${pct(p.confidence)}</div></article>`}
function matchRow(m){return `<div class="match-row"><div class="home">${esc(m.home_team_canonical_key||'Home')}</div><div class="time">${date(m.kickoff_at)}</div><div class="away">${esc(m.away_team_canonical_key||'Away')}</div><button onclick="openMatch('${encodeURIComponent(m.canonical_key)}')">View</button></div>`}
async function load(){
  try{
    const [fresh,picks,upcoming,archive,teams]=await Promise.all([get('/api/v1/data-freshness'),get(`${api}/best-picks?limit=9`),get(`${api}/matches/upcoming?limit=12`),get(`${api}/prediction-archive?limit=20`),get(`${api}/teams`)]);
    const f=fresh[0]; $('freshness').textContent=f?.last_data_at?date(f.last_data_at):'No successful update'; $('freshness-detail').textContent=f?.last_error?`Last update error: ${f.last_error}`:`${f?.display_name||'Provider'} · ${f?.freshness_policy||'periodic'} source`;
    $('picks-grid').innerHTML=picks.length?picks.map(pickCard).join(''):'<div class="detail-card empty">No persisted predictions are available yet.</div>';
    $('upcoming-list').innerHTML=upcoming.length?upcoming.map(matchRow).join(''):'<div class="detail-card empty">No upcoming fixtures are currently available.</div>';
    $('archive-list').innerHTML=archive.length?archive.map(a=>`<div class="archive-row"><div><strong>${esc(a.match_canonical_key)}</strong><br><span class="muted">${date(a.predicted_at)} · ${esc(a.model_version)}</span></div><span>${esc(a.selected_prediction)} · ${pct(a.confidence)}</span><span>${pct(a.home_probability)} / ${pct(a.draw_probability)} / ${pct(a.away_probability)}</span><span class="status ${a.is_correct===true?'good':a.is_correct===false?'bad':''}">${a.is_correct===true?'Correct':a.is_correct===false?'Incorrect':'Unresolved'}</span><span class="muted">${a.actual_result?`Result ${esc(a.actual_result)}`:'Awaiting result'}</span></div>`).join(''):'<div class="detail-card empty">No archived predictions yet.</div>';
    $('team-list').innerHTML=teams.slice(0,12).map(t=>`<article class="team-card"><p class="eyebrow">${esc(t.league_canonical_key||'League')}</p><strong>${esc(t.name)}</strong><p class="muted">${esc(t.canonical_key)}</p><button class="button" onclick="showForm('${encodeURIComponent(t.canonical_key)}')">View form</button></article>`).join('')||'<div class="detail-card empty">No canonical teams available.</div>';
    $('fixtures-list').innerHTML=upcoming.map(matchRow).join('');
  }catch(e){console.error(e);$('freshness').textContent='Unavailable';$('picks-grid').innerHTML='<div class="detail-card empty">Fovra could not reach its production data API. Check /health.</div>'}
}
window.openMatch=async function(key){location.hash='match';try{const d=await get(`${api}/matches/${key}`);const m=d.match,p=d.prediction;$('match-detail').className='detail-card';$('match-detail').innerHTML=`<p class="eyebrow">${esc(m.league_canonical_key||'MATCH')}</p><h2>${esc(m.home_team_canonical_key)} <span class="muted">vs</span> ${esc(m.away_team_canonical_key)}</h2><p class="muted">${date(m.kickoff_at)} · ${esc(m.status)} · source ${esc(m.source_provider)}</p>${p?`<div class="probabilities"><div class="prob"><span>Home</span><b>${pct(p.home_probability)}</b></div><div class="prob"><span>Draw</span><b>${pct(p.draw_probability)}</b></div><div class="prob"><span>Away</span><b>${pct(p.away_probability)}</b></div></div><p><strong>Prediction:</strong> ${esc(p.selected_prediction)} · <strong>Confidence:</strong> ${pct(p.confidence)}</p><p class="muted">Model ${esc(p.model_version)} · predicted ${date(p.predicted_at)}. This is a prediction, not the actual result.</p>`:'<p class="muted">No persisted prediction is available for this match.</p>'}`;const h=await get(`${api}/teams/${encodeURIComponent(m.home_team_canonical_key)}/h2h/${encodeURIComponent(m.away_team_canonical_key)}?limit=10`);$('h2h-detail').className='detail-card';$('h2h-detail').innerHTML=h.length?h.map(x=>`<p>${date(x.kickoff_at)} · ${esc(x.home_team_canonical_key)} ${x.home_score??'—'}–${x.away_score??'—'} ${esc(x.away_team_canonical_key)}</p>`).join(''):'<span class="muted">No completed head-to-head records.</span>'}catch(e){$('match-detail').textContent='Match details unavailable.'}};
window.showForm=async function(key){location.hash='teams';const rows=await get(`${api}/teams/${key}/form?limit=5`);$('team-list').insertAdjacentHTML('afterbegin',`<article class="detail-card"><p class="eyebrow">RECENT FORM</p>${rows.map(x=>`<p>${date(x.kickoff_at)} · ${esc(x.home_team_canonical_key)} ${x.home_score??'—'}–${x.away_score??'—'} ${esc(x.away_team_canonical_key)}</p>`).join('')||'<span class="muted">No completed matches.</span>'}</article>`) }
document.addEventListener('DOMContentLoaded',load);
